// @flow
import string from '../generator/methods/string';
import number from '../generator/methods/number';
import date from '../generator/methods/date';
import list from '../generator/methods/list';

const tableMap: Object = new Map([
  [ 'name', () => string.lorem({ count: 1, type: 'word', }), ],
  [ 'id', () => string.id(), ],
  [ 'symbol', () => string.word({ upperCase: true, minLength: 4, maxLength: 8, }), ],
  [ 'type', () => string.enum([ 'index', 'bond', 'stock', 'options', 'mtf', 'etf', 'currency', ]), ],
  [ 'value', () => number.float({ max: 15000, min: 20, fixed: 2, }), ],
  [ 'USDValue', () => number.float({}), ],
  [ 'baseValue', () => number.float({}), ],
  [ 'openingValue', () => number.float({}), ],
  [ 'maxValue', () => number.float({}), ],
  [ 'minValue', () => number.float({}), ],
  [ 'changePercentage', () => number.float({}), ],
  [ 'lastTradeTime', () => date.timestamp({}), ],
  [ 'tradingStatus', () => string.enum([ 'רציף', 'נעולה', 'סגורה', 'טרום נעילה', 'טרום פתיחה', ]), ],
  [ 'volume', () => number.float({}), ],
  [ 'arbGap', () => number.float({}), ],
  [ 'openPositions', () => number.float({}), ],
  [ 'putCallRatio', () => number.float({}), ],
  [ 'avgDuration', () => number.float({}), ],
  [ 'purchasePrice', () => number.float({}), ],
  [ 'redemptionPrice', () => number.float({}), ],
  [ 'redemptionYield', () => number.float({}), ],
  [ 'yieldToMaturity', () => number.float({}), ],
  [ 'dailyYield', () => number.float({}), ],
  [ 'weeklyYield', () => number.float({}), ],
  [ 'monthlyYield', () => number.float({}), ],
  [ 'quarterlyYield', () => number.float({}), ],
  [ 'yearlyYield', () => number.float({}), ],
  [ 'threeYearsYield', () => number.float({}), ],
  [ 'fiveYearsYield', () => number.float({}), ],
  [ 'maxYield', () => number.float({}), ],
  [ 'dailyParentYield', () => number.float({}), ],
  [ 'weeklyParentYield', () => number.float({}), ],
  [ 'monthlyParentYield', () => number.float({}), ],
  [ 'quarterlyParentYield', () => number.float({}), ],
  [ 'yearlyParentYield', () => number.float({}), ],
  [ 'threeYearsParentYield', () => number.float({}), ],
  [ 'fiveYearsParentYield', () => number.float({}), ],
  [ 'maxParentYield', () => number.float({}), ],
  [ 'dailyAvgMtfYield', () => number.float({}), ],
  [ 'weeklyAvgMtfYield', () => number.float({}), ],
  [ 'monthlyAvgMtfYield', () => number.float({}), ],
  [ 'quarterlyAvgMtfYield', () => number.float({}), ],
  [ 'yearlyAvgMtfYield', () => number.float({}), ],
  [ 'threeYearsAvgMtfYield', () => number.float({}), ],
  [ 'fiveYearsAvgMtfYield', () => number.float({}), ],
  [ 'maxAvgMtfYield', () => number.float({}), ],
  [ 'managementFee', () => number.float({}), ],
  [ 'inflows', () => number.float({}), ],
  [ 'outflows', () => number.float({}), ],
  [ 'mtfBeat', () => list(
    [
      {
        method: number.int,
        options: { max: 5, },
      },
    ],
    3
  ), ],
  [ 'standardDeviation', () => number.float({}), ],
  [ 'peRatio', () => number.float({}), ],
  [ 'pbRatio', () => number.float({}), ],
  [ 'psRatio', () => number.float({}), ],
  [ 'dailyAvgVolume', () => number.float({}), ],
  [ 'issuerName', () => string.word({}), ],
  [ 'marketCap', () => number.float({}), ],
  [ 'roe', () => number.float({}), ],
  [ 'netProfitMargin', () => number.float({}), ],
  [ 'capitalBalanceRatio', () => number.float({}), ],
  [ 'per', () => number.float({}), ],
  [ 'yieldFactor', () => number.float({}), ],
  [ 'daysToMaturity', () => number.int({}), ],
  [ 'classification', () => string.word({}), ],
  [ 'issueDate', () => date.timestamp({}), ],
  [ 'redemptionDate', () => date.timestamp({}), ],
  [ 'periodicalInterest', () => number.float({}), ],
  [ 'periodicalInterestDate', () => number.float({}), ],
  [ 'yearlyInterest', () => number.float({}), ],
  [ 'retailTax', () => number.float({}), ],
  [ 'linkageType', () => string.word({}), ],
  [ 'parentId', () => string.id(), ],
  [ 'parentName', () => string.word({ minLength: 3, capital: true, upperCase: true, }), ],
  [ 'paymentDate', () => date.timestamp({}), ],
  [ 'exDate', () => date.timestamp({}), ],
  [ 'redemptionRate', () => number.float({}), ],
  [ 'holdingsRatio', () => number.float({}), ],
]);

export default tableMap;
