version: '3.4'
services:
  htz_graphql:
    hostname: htz-graphql
    build:
      context: .
      args:
        NEXT_BUILD_ID: ${version:-latest}
    image: 'nexus-ng.themarker.com/htz-graphql:${version:-latest}'
    ports:
    - 3209:3209
    command: ['yarn', 'workspace', '@haaretz/haaretz.co.il', 'start:gql']
    environment:
    - NODE_ENV=production
    - CONNECTION_PRESET=prod
    - NEXT_BUILD_ID=${NEXT_BUILD_ID:-latest}
    # the following environment is optional
    - PORT=3209
    - GRAPHQL_PORT=3209
    - BIND_ADDRESS=react-stage
    - HOSTNAME=react-stage
    - GRAPHQL_USE_SSL=true
    - GRAPHQL_EXPOSE_PORT=false
    - GRAPHQL_SUB_DOMAIN=grahpql-prod
    - ENGINE_API_KEY=service:htz-stage:6hYWWng421ai05_ERxSikQ

    networks:
    - production

networks:
  production:
    external: true
