import React from 'react';
import PropTypes from 'prop-types';
import { FelaTheme, createComponent, } from 'react-fela';
import { parseComponentProp, } from '@haaretz/htz-css-tools';
import getComponent from '../../utils/componentFromInputTemplate';
import ArticleImage from '../ArticleImage/ArticleImage';
import Caption from '../Caption/Caption';
import Section from '../AutoLevels/Section';

const propTypes = {
  /**
   * The elements composing the article’s body.
   */
  body: PropTypes.arrayOf(
    PropTypes.oneOfType([ PropTypes.string, PropTypes.object, ])
  ).isRequired,
  /** Class(es) to be added to the DOM element.
   * Automatically generated by Fela, do not enter manually.
   */
  className: PropTypes.string,
};

const defaultProps = {
  className: null,
};

const mediaQueryCallback = (prop, value) => ({ [prop]: value, });

const figureStyle = ({ theme, lastItem, }) =>
  (!lastItem
    ? {
      ...parseComponentProp(
        'marginBottom',
        theme.articleStyle.body.marginBottom,
        theme.mq,
        mediaQueryCallback
      ),
    }
    : {});
const Figure = createComponent(figureStyle, 'figure');

const asideStyle = ({ theme, }) => ({
  ...theme.mq(
    { from: 'l', },
    {
      width: '26rem',
      position: 'absolute',
      textAlign: 'end',
      start: '-6rem',
      transform: 'translateX(100%)',
    }
  ),
  extend: [
    ...[
      parseComponentProp(
        'marginBottom',
        theme.articleStyle.body.marginBottom,
        theme.mq,
        mediaQueryCallback
      ),
    ],
  ],
});
const Aside = createComponent(asideStyle, 'aside');

const bodyWrapperStyle = ({ theme, }) => ({
  position: 'relative',
});

const BodyWrapper = createComponent(bodyWrapperStyle, Section);

const buildComponent = (context, index, isLastItem) => {
  const uniqueId =
    context.elementType || context.inputTemplate || context.tag || null;
  const Component =
    uniqueId === 'com.tm.Image' ? ArticleImage : getComponent(uniqueId);

  switch (uniqueId) {
    case 'com.tm.Image':
      return <Component key={index} lastItem={isLastItem} {...context} />;
    case 'embedElement':
    case 'interactiveElement':
    case 'com.tm.ImageGalleryElement':
    case 'com.tm.Video': // eslint-disable-line no-case-declarations
      return (
        <Figure key={index} lastItem={isLastItem}>
          <Component {...context} />
          {(context.title || context.caption || context.credit) && (
            <Caption
              caption={context.title || context.caption}
              credit={context.credit}
            />
          )}
        </Figure>
      );
    case 'com.htz.MagazineArticleQuote':
      return (
        <Aside key={index}>
          <Component {...context} />
        </Aside>
      );
    case 'com.polobase.DfpBannerElement':
      return <Component {...context} {...context.properties} />;
    default:
      return (
        <FelaTheme
          render={theme => (
            <Component
              key={index}
              {...context}
              miscStyles={
                isLastItem
                  ? null
                  : parseComponentProp(
                      'marginBottom',
                      theme.articleStyle.body.marginBottom,
                      theme.mq,
                      mediaQueryCallback
                    )
              }
              renderFirstImpression
            />
          )}
        />
      );
  }
};

function ArticleBody({ body, className, }) {
  return (
    <BodyWrapper className={className}>
      {body.map((component, i) =>
        buildComponent(component, i, i === body.length - 1)
      )}
    </BodyWrapper>
  );
}

ArticleBody.propTypes = propTypes;
ArticleBody.defaultProps = defaultProps;

export default ArticleBody;
