export default {
  adSlotConfig: {
    'Finance.TheMarker.com.Billboard': {
      id: 'Finance.TheMarker.com.Billboard',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 970, 250, ], [ 960, 150, ], [ 970, 90, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 0, 0, ], ],
        m: [ [ 468, 60, ], ],
        l: [ [ 970, 250, ], [ 960, 150, ], [ 970, 90, ], ],
        xl: [ [ 970, 250, ], [ 960, 150, ], [ 970, 90, ], ],
        xxl: [ [ 970, 250, ], [ 960, 150, ], [ 970, 90, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.Banner1': {
      id: 'Finance.TheMarker.com.Banner1',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 300, 250, ], [ 468, 60, ], [ 728, 90, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 300, 250, ], ],
        m: [ [ 300, 250, ], [ 468, 60, ], ],
        l: [ [ 728, 90, ], ],
        xl: [ [ 728, 90, ], [ 300, 250, ], ],
        xxl: [ [ 728, 90, ], [ 300, 250, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.Banner2': {
      id: 'Finance.TheMarker.com.Banner2',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 300, 250, ], [ 468, 60, ], [ 728, 90, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 300, 250, ], ],
        m: [ [ 300, 250, ], [ 468, 60, ], ],
        l: [ [ 728, 90, ], [ 300, 250, ], ],
        xl: [ [ 728, 90, ], ],
        xxl: [ [ 728, 90, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.Banner3': {
      id: 'Finance.TheMarker.com.Banner3',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 300, 250, ], [ 160, 600, ], [ 728, 90, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 300, 250, ], ],
        m: [ [ 300, 250, ], ],
        l: [ [ 160, 600, ], [ 728, 90, ], [ 300, 250, ], ],
        xl: [ [ 160, 600, ], [ 300, 250, ], ],
        xxl: [ [ 160, 600, ], [ 300, 250, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.HalfPage': {
      id: 'Finance.TheMarker.com.HalfPage',
      responsive: false,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 300, 600, ], ],
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    // רביעיית תוכן מקודם
    'Finance.TheMarker.com.Native1': {
      id: 'Finance.TheMarker.com.Native1',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 212, 126, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 212, 126, ], ],
        m: [ [ 212, 126, ], ],
        l: [ [ 212, 126, ], ],
        xl: [ [ 212, 126, ], ],
        xxl: [ [ 212, 126, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.Native2': {
      id: 'Finance.TheMarker.com.Native2',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 212, 126, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 212, 126, ], ],
        m: [ [ 212, 126, ], ],
        l: [ [ 212, 126, ], ],
        xl: [ [ 212, 126, ], ],
        xxl: [ [ 212, 126, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.Native3': {
      id: 'Finance.TheMarker.com.Native3',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 212, 126, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 212, 126, ], ],
        m: [ [ 212, 126, ], ],
        l: [ [ 212, 126, ], ],
        xl: [ [ 212, 126, ], ],
        xxl: [ [ 212, 126, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.Native4': {
      id: 'Finance.TheMarker.com.Native4',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 212, 126, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 212, 126, ], ],
        m: [ [ 212, 126, ], ],
        l: [ [ 212, 126, ], ],
        xl: [ [ 212, 126, ], ],
        xxl: [ [ 212, 126, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },

    'Finance.TheMarker.com.InListNative': {
      id: 'Finance.TheMarker.com.InListNative',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 124, 91, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 124, 91, ], ],
        m: [ [ 124, 91, ], ],
        l: [ [ 124, 91, ], ],
        xl: [ [ 124, 91, ], ],
        xxl: [ [ 124, 91, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },

    'Finance.TheMarker.com.StripBottom': {
      id: 'Finance.TheMarker.com.StripBottom',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 320, 50, ], [ 468, 60, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 320, 50, ], ],
        m: [ [ 468, 60, ], ],
        l: [ [ 468, 60, ], ],
        xl: [ [ 468, 60, ], ],
        xxl: [ [ 468, 60, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },

    // בנק לאומי
    'Finance.TheMarker.com.FujiRight': {
      id: 'Finance.TheMarker.com.FujiRight',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 212, 144, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 0, 0, ], ],
        m: [ [ 0, 0, ], ],
        l: [ [ 212, 144, ], ],
        xl: [ [ 212, 144, ], ],
        xxl: [ [ 212, 144, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.FujiLeft': {
      id: 'Finance.TheMarker.com.FujiLeft',
      responsive: true,
      fluid: true,
      priority: 'normal',
      adSizeMapping: [ [ 212, 144, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 0, 0, ], ],
        m: [ [ 0, 0, ], ],
        l: [ [ 212, 144, ], ],
        xl: [ [ 212, 144, ], ],
        xxl: [ [ 212, 144, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    // IR
    'Finance.TheMarker.com.KodakRight': {
      id: 'Finance.TheMarker.com.KodakRight',
      responsive: true,
      fluid: false,
      priority: 'normal',
      adSizeMapping: [ [ 212, 162, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 0, 0, ], ],
        m: [ [ 0, 0, ], ],
        l: [ [ 212, 162, ], ],
        xl: [ [ 212, 162, ], ],
        xxl: [ [ 212, 162, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
    'Finance.TheMarker.com.KodakLeft': {
      id: 'Finance.TheMarker.com.KodakLeft',
      responsive: true,
      fluid: true,
      priority: 'normal',
      adSizeMapping: [ [ 212, 162, ], ],
      responsiveAdSizeMapping: {
        xxs: [ [ 0, 0, ], ],
        xs: [ [ 0, 0, ], ],
        s: [ [ 0, 0, ], ],
        m: [ [ 0, 0, ], ],
        l: [ [ 212, 162, ], ],
        xl: [ [ 212, 162, ], ],
        xxl: [ [ 212, 162, ], ],
      },
      refreshTime: '',
      blacklistReferrers: '',
      whitelistReferrers: '',
    },
  },
  adManagerConfig: {
    network: '9401',
    adUnitBase: 'themarker.com.mobile_web',
  },
  conflictManagementConfig: {
    'themarker.com.mobile_web.box1.article': [ {
      onsize: '320x400',
      avoid: 'themarker.com.mobile_web.strip_bottom',
    },
    ],
    'themarker.com.mobile_web.strip_bottom': [ {
      onsize: '360x120',
      avoid: 'themarker.com.mobile_web.top',
    },
    ],
    'themarker.com.mobile_web.top': [],
  },
  impressionManagerConfig: {
    'themarker.com.mobile_web.splash_all': {
      id: 'themarker.com.mobile_web.splash',
      target: 'all',
      frequency: '7/1hour',
    },
    'themarker.com.mobile_web.top_all': {
      id: 'themarker.com.mobile_web.top',
      target: 'all',
      frequency: '30/1hour',
    },
    'themarker.com.web.halfpage.floating_x_homepage': {
      id: 'themarker.com.web.halfpage.floating_x',
      target: 'homepage',
      frequency: '10/1day',
    },
    'themarker.com.web.halfpage.floating_x_section': {
      id: 'themarker.com.web.halfpage.floating_x',
      target: 'section',
      frequency: '10/1day',
    },
    'themarker.com.web.inread_all': {
      id: 'themarker.com.web.inread',
      target: 'all',
      frequency: '1000/1day',
    },
    'themarker.com.web.maavaron_all': {
      id: 'themarker.com.web.maavaron',
      target: 'all',
      frequency: '10/1day',
    },
    'themarker.com.web.popunder_all': {
      id: 'themarker.com.web.popunder',
      target: 'all',
      frequency: '0/4hour',
    },
    'themarker.com.web.ruler_homepage': {
      id: 'themarker.com.web.ruler',
      target: 'homepage',
      frequency: '4/1day',
    },
    'themarker.com.web.ruler_section': {
      id: 'themarker.com.web.ruler',
      target: 'section',
      frequency: '4/1day',
    },
    'themarker.com.web.textlink.hp.fast_news.2_all': {
      id: 'themarker.com.web.textlink.hp.fast_news.2',
      target: 'all',
      frequency: '0/1day',
    },
  },
  googleGlobalSettings: {
    enableSingleRequest: false,
    enableAsyncRendering: true,
    breakpointType: 'type4',
  },
};
