import React from 'react';
import { createComponent, } from 'react-fela';
import PropTypes from 'prop-types';
import { parseComponentProp, parseStyleProps, } from '@haaretz/htz-css-tools';
import { attrsPropType, } from '../../propTypes/attrsPropType';
import { stylesPropType, } from '../../propTypes/stylesPropType';

const propTypes = {
  /**
   * An object of attrbutes to set on the DOM element.
   * Passed to the underlying react element
   */
  attrs: attrsPropType,
  /**
   * backgroundColor that will trump the default backgroundColor defined in the theme
   */
  bgc: PropTypes.string,
  /** The Children to be rendered inside a `<LayoutContainer>` */
  children: PropTypes.node,
  /** Class(es) to be added to the DOM element.
   * Automatically generated by Fela, do not enter manually.
   */
  className: PropTypes.string,
  /**
   * A special property holding miscellaneous CSS values that
   * trump all default values. Processed by
   * [`parseStyleProps`](https://Haaretz.github.io/htz-frontend/htz-css-tools#parsestyleprops)
   */
  miscStyles: stylesPropType,
};

const defaultProps = {
  attrs: null,
  bgc: null,
  children: null,
  className: null,
  miscStyles: null,
};

const styles = ({ bgc, miscStyles, theme, }) => ({
  backgroundColor: bgc || theme.color('primary', '-6'),
  marginRight: 'auto',
  marginLeft: 'auto',
  width: '100%',
  extend: [
    parseComponentProp(
      'maxWidth',
      [
        { from: 's', until: 'm', value: 100, },
        { from: 'm', until: 'l', value: 768 / 6, },
        { from: 'l', until: 'xl', value: 1024 / 6, },
        { from: 'xl', value: 1293 / 7, },
      ],
      theme.mq
    ),
    ...(miscStyles ? parseStyleProps(miscStyles, theme.mq, theme.type) : []),
  ],
});

export function LayoutContainter({ attrs, children, className, }) {
  return (
    <div className={className} {...attrs}>
      {children}
    </div>
  );
}

LayoutContainter.propTypes = propTypes;
LayoutContainter.defaultProps = defaultProps;

export default createComponent(styles, LayoutContainter, [ 'attrs', 'children', ]);
